### ISSUE TITLE
Issue after building the project

### ISSUE THREAD

**Issue by ninjadev106** [BorisPerkovic/Ecommerce-ReactNative#7]
Hi Boris,
I've found your good example from Github and tried to compile the project. The build process is successful, but it gives an error at the beginning of app installation. 
Invariant Violation: "Ecommerce" has not been registered. This can happen if: 
*Metro(the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
*A module failed to load due to an error and 'AppRegistry.registerComponent' wasn't called.,
.....

I did some research to fix the issue and tried to adjust several solutions such as app name lowercase, but I didn't get it fixed. I hope you can help me with that.

**Comment by BorisPerkovic** [comment]
Hi ninjadev106, hope you feel good!
Thank you for your feedback.

I have cloned this project on my PC and installed dependencies with npm(yarn) install, and this is what I got:
- after  npm(yarn) android, app started on android without any problems, so there is no need for further steps for android
- on ios is a bit different, after  npm(yarn) ios, you have to do this couple of steps:
cd ios
pod install
cd ../
........
Also, you need to create .env file into your root folder. That is the place where i store all my endpoints. For the endpoints(URLs), please contact me on linkedin or facebook to a private message.

https://www.linkedin.com/in/perkovicboris/

https://www.facebook.com/boris.pekovic.7
......
When you finish this setup, you need to kill the app and reset cache with: react-native start --reset-cache

Now you can start app both on android or ios. This works for me. Please, give me a feedback if everything is ok.

**Comment by ninjadev106** [comment]
Hi Boris,
Yes, it works properly for me now. 

Thank you for the help!

**Comment by BorisPerkovic** [comment]
Nice, happy to hear that :D.

I will close this issues, seems problem is solved.
